import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dir, '..', '..', '..');
const dist = join(root, 'apps/client/dist');
const built = await Bun.build({
  entrypoints: [join(root, 'apps/client/src/main.tsx')],
  outdir: dist,
  target: 'browser',
});
if (!built.success) {
  console.error(built.logs);
  throw new Error('client build failed');
}

const files: Record<string, string> = {};
for (const name of readdirSync(dist)) {
  if (!/^[A-Za-z0-9._-]+$/.test(name)) continue;
  files[name] = readFileSync(join(dist, name)).toString('base64');
}

const shell = readFileSync(join(root, 'apps/client/index.html'), 'utf8');
const body = `// Generated by apps/guest/scripts/embed-assets.ts. The guest has no filesystem.

export const pageShell = ${JSON.stringify(shell)};

export const assetFiles: Record<string, string> = ${JSON.stringify(files)};
`;

writeFileSync(join(import.meta.dir, '../src/embedded-assets.ts'), body);
