/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/account/identity-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** apiList */
        get: operations["apiList"];
        put?: never;
        post?: never;
        /** apiUnlink */
        delete: operations["apiUnlink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/identity-links/unlink/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** apiPrepareUnlink */
        post: operations["apiPrepareUnlink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /** Archive a user */
        delete: operations["archiveUser"];
        options?: never;
        head?: never;
        /** Update a user's display name */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit records */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/oauth-clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all OAuth clients */
        get: operations["oauthClients"];
        put?: never;
        /** Create an OAuth client */
        post: operations["createOAuthClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all organizations */
        get: operations["organizations"];
        put?: never;
        /** Create an organization */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["users"];
        put?: never;
        /** Create a user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{slug}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an organization membership */
        get: operations["getMembership"];
        /** Upsert organization membership */
        put: operations["putMembership"];
        post?: never;
        /** Remove organization membership */
        delete: operations["deleteMembership"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an organization */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        /** Delete an organization */
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        /** Update an organization's display name */
        patch: operations["updateOrganization"];
        trace?: never;
    };
    "/api/admin/oauth-clients/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an OAuth client */
        get: operations["getOAuthClient"];
        /** Update OAuth client metadata */
        put: operations["updateOAuthClient"];
        post?: never;
        /** Revoke an OAuth client */
        delete: operations["revokeOAuthClient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/oauth-clients/{clientId}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate an OAuth client secret */
        post: operations["rotateOAuthClientSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organization members
         * @description Returns a paginated list of members for the specified organization slug.
         */
        get: operations["members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MembershipRequest: {
            userId?: string;
            role?: string;
        };
        UpdateOAuthClientRequest: {
            organizationSlug?: string;
            redirectUris?: string[];
            scopes?: string[];
            browser?: boolean;
        };
        OAuthClientResponse: {
            client_id?: string;
            organization_slug?: string;
            redirect_uris?: string[];
            scopes?: string[];
            browser?: boolean;
            /** Format: date-time */
            revoked_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        CreateUserRequest: {
            login?: string;
            email?: string;
            displayName?: string;
        };
        UserCreatedResponse: {
            id?: string;
            status?: string;
        };
        CreateOrganizationRequest: {
            slug?: string;
            name?: string;
        };
        OrganizationCreatedResponse: {
            id?: string;
            slug?: string;
        };
        CreateOAuthClientRequest: {
            clientId?: string;
            organizationSlug?: string;
            redirectUris?: string[];
            scopes?: string[];
            browser?: boolean;
        };
        OAuthClientSecretResponse: {
            client_id?: string;
            client_secret?: string;
        };
        RotateOAuthClientSecretRequest: {
            version?: string;
        };
        UpdateUserRequest: {
            displayName?: string;
        };
        UserResponse: {
            id?: string;
            login?: string;
            email?: string;
            display_name?: string;
            email_verified?: boolean;
            status?: string;
        };
        UpdateOrganizationRequest: {
            name?: string;
        };
        OrganizationResponse: {
            id?: string;
            slug?: string;
            name?: string;
            /** Format: date-time */
            created_at?: string;
        };
        DirectoryMemberResponse: {
            issuer?: string;
            subject?: string;
            login?: string;
            display_name?: string;
            picture?: string;
            email?: string;
            email_verified?: boolean;
            organization_role?: string;
        };
        DirectoryMembersPageResponse: {
            items?: components["schemas"]["DirectoryMemberResponse"][];
            next_cursor?: string;
        };
        IdentityLinkView: {
            /** Format: uuid */
            id?: string;
            providerName?: string;
            issuer?: string;
            subjectHint?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MembershipResponse: {
            organization_slug?: string;
            user_id?: string;
            role?: string;
        };
        AuditRecordResponse: {
            id?: string;
            action?: string;
            actor_client_id?: string;
            target?: string;
            correlation_id?: string;
            before_metadata?: string;
            after_metadata?: string;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apiList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        providerName?: string;
                        issuer?: string;
                        subjectHint?: string;
                        /** Format: date-time */
                        createdAt?: string;
                        /** Format: date-time */
                        updatedAt?: string;
                    }[];
                };
            };
        };
    };
    apiUnlink: {
        parameters: {
            query: {
                issuer: string;
                subject: string;
                confirmationToken: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    apiPrepareUnlink: {
        parameters: {
            query: {
                issuer: string;
                subject: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get a user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        login?: string;
                        email?: string;
                        display_name?: string;
                        email_verified?: boolean;
                        status?: string;
                    };
                };
            };
        };
    };
    archiveUser: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archive a user */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string;
                };
            };
        };
        responses: {
            /** @description Update a user's display name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        login?: string;
                        email?: string;
                        display_name?: string;
                        email_verified?: boolean;
                        status?: string;
                    };
                };
            };
        };
    };
    audit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List audit records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        action?: string;
                        actor_client_id?: string;
                        target?: string;
                        correlation_id?: string;
                        before_metadata?: string;
                        after_metadata?: string;
                        /** Format: date-time */
                        created_at?: string;
                    }[];
                };
            };
        };
    };
    oauthClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all OAuth clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_id?: string;
                        organization_slug?: string;
                        redirect_uris?: string[];
                        scopes?: string[];
                        browser?: boolean;
                        /** Format: date-time */
                        revoked_at?: string;
                        /** Format: date-time */
                        created_at?: string;
                    }[];
                };
            };
        };
    };
    createOAuthClient: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    clientId?: string;
                    organizationSlug?: string;
                    redirectUris?: string[];
                    scopes?: string[];
                    browser?: boolean;
                };
            };
        };
        responses: {
            /** @description Create an OAuth client */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_id?: string;
                        client_secret?: string;
                    };
                };
            };
        };
    };
    organizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        slug?: string;
                        name?: string;
                        /** Format: date-time */
                        created_at?: string;
                    }[];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug?: string;
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Create an organization */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        slug?: string;
                    };
                };
            };
        };
    };
    users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        login?: string;
                        email?: string;
                        display_name?: string;
                        email_verified?: boolean;
                        status?: string;
                    }[];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    login?: string;
                    email?: string;
                    displayName?: string;
                };
            };
        };
        responses: {
            /** @description Create a user */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        status?: string;
                    };
                };
            };
        };
    };
    getMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get an organization membership */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organization_slug?: string;
                        user_id?: string;
                        role?: string;
                    };
                };
            };
        };
    };
    putMembership: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                slug: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userId?: string;
                    role?: string;
                };
            };
        };
        responses: {
            /** @description Upsert organization membership */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteMembership: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                slug: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Remove organization membership */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get an organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        slug?: string;
                        name?: string;
                        /** Format: date-time */
                        created_at?: string;
                    };
                };
            };
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete an organization */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Update an organization's display name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        slug?: string;
                        name?: string;
                        /** Format: date-time */
                        created_at?: string;
                    };
                };
            };
        };
    };
    getOAuthClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get an OAuth client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_id?: string;
                        organization_slug?: string;
                        redirect_uris?: string[];
                        scopes?: string[];
                        browser?: boolean;
                        /** Format: date-time */
                        revoked_at?: string;
                        /** Format: date-time */
                        created_at?: string;
                    };
                };
            };
        };
    };
    updateOAuthClient: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    organizationSlug?: string;
                    redirectUris?: string[];
                    scopes?: string[];
                    browser?: boolean;
                };
            };
        };
        responses: {
            /** @description Update OAuth client metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_id?: string;
                        organization_slug?: string;
                        redirect_uris?: string[];
                        scopes?: string[];
                        browser?: boolean;
                        /** Format: date-time */
                        revoked_at?: string;
                        /** Format: date-time */
                        created_at?: string;
                    };
                };
            };
        };
    };
    revokeOAuthClient: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoke an OAuth client */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotateOAuthClientSecret: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version?: string;
                };
            };
        };
        responses: {
            /** @description Rotate an OAuth client secret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        client_id?: string;
                        client_secret?: string;
                    };
                };
            };
        };
    };
    members: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List organization members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["DirectoryMemberResponse"][];
                        next_cursor?: string;
                    };
                };
            };
        };
    };
}
