/**
 * Generate TypeScript types, and the users response schema, from api/v1/openapi.yaml.
 * `oas` supplies the operation JSON Schema. Component object schemas become interfaces.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import Oas from 'oas';
import OASNormalize from 'oas-normalize';

const root = resolve(import.meta.dir, '..');
const specPath = resolve(root, 'api/v1/openapi.yaml');
const outPath = resolve(root, 'src/contracts/openapi.types.ts');

const spec = await new OASNormalize(specPath, { enablePaths: true }).load();
const oas = Oas.init(spec);
const users = oas.getOperationById('users');
if (!users || !('getResponseAsJSONSchema' in users))
  throw new Error('OpenAPI operation users was not found');

const response = users.getResponseAsJSONSchema(200)?.[0]?.schema;
if (!response) throw new Error('operation users has no JSON response schema');

const components = componentSchemas(spec);
const usersResponseSchema = dereference(response, components);

const interfaces = Object.entries(components)
  .map(([name, schema]) => interfaceFor(name, schema))
  .join('\n\n');

const source = `// @generated by scripts/generate-oas-types.ts — do not edit.
import type { JsonSchema } from "../codegen/contract.ts";

${interfaces}

/** Response body for GET /api/admin/users (operationId users). */
export type UsersResponse = UserResponse[];

/** JSON Schema for {@link UsersResponse}, taken from the oas response schema. */
export const usersResponseSchema: JsonSchema = ${JSON.stringify(usersResponseSchema, null, 2)};
`;

mkdirSync(resolve(root, 'src/contracts'), { recursive: true });
writeFileSync(outPath, source);
console.log(`wrote ${outPath}`);

function componentSchemas(
  document: Record<string, unknown>,
): Record<string, Record<string, unknown>> {
  const components = document.components;
  if (!isRecord(components) || !isRecord(components.schemas))
    throw new Error('OpenAPI document has no components.schemas');
  const schemas: Record<string, Record<string, unknown>> = {};
  for (const [name, schema] of Object.entries(components.schemas)) {
    if (!isRecord(schema)) throw new Error(`component schema ${name} is not an object`);
    schemas[name] = schema;
  }
  return schemas;
}

function interfaceFor(name: string, schema: Record<string, unknown>): string {
  if (schema.type !== 'object' || !isRecord(schema.properties)) {
    throw new Error(`component schema ${name} is not an object with properties`);
  }
  const fields = Object.entries(schema.properties).map(([property, value]) => {
    if (!isRecord(value)) throw new Error(`${name}.${property} is not a schema`);
    return `  ${property}?: ${tsType(value)};`;
  });
  return `export interface ${name} {\n${fields.join('\n')}\n}`;
}

function tsType(schema: Record<string, unknown>): string {
  const ref = schema.$ref;
  if (typeof ref === 'string') {
    const name = ref.split('/').pop();
    if (!name) throw new Error(`unsupported $ref ${ref}`);
    return name;
  }
  switch (schema.type) {
    case 'string':
      return 'string';
    case 'boolean':
      return 'boolean';
    case 'integer':
    case 'number':
      return 'number';
    case 'array': {
      if (!isRecord(schema.items))
        throw new Error(`array schema is missing items: ${JSON.stringify(schema)}`);
      return `${tsType(schema.items)}[]`;
    }
    default:
      throw new Error(`unsupported schema ${JSON.stringify(schema)}`);
  }
}

/** Drop oas bookkeeping and inline component $refs so the schema matches the OpenAPI response body. */
function dereference(
  schema: unknown,
  components: Record<string, Record<string, unknown>>,
  stack: string[] = [],
): unknown {
  if (Array.isArray(schema)) return schema.map((item) => dereference(item, components, stack));
  if (!isRecord(schema)) return schema;

  const ref = schema.$ref;
  if (typeof ref === 'string') {
    if (stack.includes(ref)) throw new Error(`cyclic $ref ${ref}`);
    const name = ref.split('/').pop();
    const target = name ? components[name] : undefined;
    if (!target) throw new Error(`unresolved $ref ${ref}`);
    return dereference(target, components, [...stack, ref]);
  }

  const resolved: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(schema)) {
    if (key === '$schema' || key === 'components' || key === 'x-readme-ref-name') continue;
    resolved[key] = dereference(value, components, stack);
  }
  return resolved;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
