// @generated by packages/codegen/scripts/generate-oas-types.ts — do not edit.
import type { JsonSchema } from '../contract.ts';

export interface MembershipRequest {
  userId?: string;
  role?: string;
}

export interface UpdateOAuthClientRequest {
  organizationSlug?: string;
  redirectUris?: string[];
  scopes?: string[];
  browser?: boolean;
}

export interface OAuthClientResponse {
  client_id?: string;
  organization_slug?: string;
  redirect_uris?: string[];
  scopes?: string[];
  browser?: boolean;
  revoked_at?: string;
  created_at?: string;
}

export interface CreateUserRequest {
  login?: string;
  email?: string;
  displayName?: string;
}

export interface UserCreatedResponse {
  id?: string;
  status?: string;
}

export interface CreateOrganizationRequest {
  slug?: string;
  name?: string;
}

export interface OrganizationCreatedResponse {
  id?: string;
  slug?: string;
}

export interface CreateOAuthClientRequest {
  clientId?: string;
  organizationSlug?: string;
  redirectUris?: string[];
  scopes?: string[];
  browser?: boolean;
}

export interface OAuthClientSecretResponse {
  client_id?: string;
  client_secret?: string;
}

export interface RotateOAuthClientSecretRequest {
  version?: string;
}

export interface UpdateUserRequest {
  displayName?: string;
}

export interface UserResponse {
  id?: string;
  login?: string;
  email?: string;
  display_name?: string;
  email_verified?: boolean;
  status?: string;
}

export interface UpdateOrganizationRequest {
  name?: string;
}

export interface OrganizationResponse {
  id?: string;
  slug?: string;
  name?: string;
  created_at?: string;
}

export interface DirectoryMemberResponse {
  issuer?: string;
  subject?: string;
  login?: string;
  display_name?: string;
  picture?: string;
  email?: string;
  email_verified?: boolean;
  organization_role?: string;
}

export interface DirectoryMembersPageResponse {
  items?: DirectoryMemberResponse[];
  next_cursor?: string;
}

export interface IdentityLinkView {
  id?: string;
  providerName?: string;
  issuer?: string;
  subjectHint?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface MembershipResponse {
  organization_slug?: string;
  user_id?: string;
  role?: string;
}

export interface AuditRecordResponse {
  id?: string;
  action?: string;
  actor_client_id?: string;
  target?: string;
  correlation_id?: string;
  before_metadata?: string;
  after_metadata?: string;
  created_at?: string;
}

/** Response body for GET /api/admin/users (operationId users). */
export type UsersResponse = UserResponse[];

/** JSON Schema for {@link UsersResponse}, taken from the oas response schema. */
export const usersResponseSchema: JsonSchema = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
      login: {
        type: 'string',
      },
      email: {
        type: 'string',
      },
      display_name: {
        type: 'string',
      },
      email_verified: {
        type: 'boolean',
      },
      status: {
        type: 'string',
      },
    },
  },
};
