import {
  AuditRecords,
  CreateOAuthClientRequest,
  CreateOrganizationRequest,
  CreateUserRequest,
  Empty,
  MembershipRequest,
  MembershipResponse,
  OAuthClientResponse,
  OAuthClientSecretResponse,
  OAuthClients,
  OrganizationCreatedResponse,
  OrganizationResponse,
  Organizations,
  RotateOAuthClientSecretRequest,
  UpdateOAuthClientRequest,
  UpdateOrganizationRequest,
  UpdateUserRequest,
  UserCreatedResponse,
  UserResponse,
  Users,
} from './api.schemas.ts';
import { idempotency, manifest, operation } from './manifest.ts';

const schema = { module: './api.schemas.ts' };

export default manifest(
  'admin',
  '/api/admin',
  {
    Empty: { schema: Empty, ...schema },
    Users: { schema: Users, ...schema },
    UserResponse: { schema: UserResponse, ...schema },
    UserCreatedResponse: { schema: UserCreatedResponse, ...schema },
    CreateUserRequest: { schema: CreateUserRequest, ...schema },
    UpdateUserRequest: { schema: UpdateUserRequest, ...schema },
    Organizations: { schema: Organizations, ...schema },
    OrganizationResponse: { schema: OrganizationResponse, ...schema },
    OrganizationCreatedResponse: { schema: OrganizationCreatedResponse, ...schema },
    CreateOrganizationRequest: { schema: CreateOrganizationRequest, ...schema },
    UpdateOrganizationRequest: { schema: UpdateOrganizationRequest, ...schema },
    MembershipRequest: { schema: MembershipRequest, ...schema },
    MembershipResponse: { schema: MembershipResponse, ...schema },
    OAuthClients: { schema: OAuthClients, ...schema },
    OAuthClientResponse: { schema: OAuthClientResponse, ...schema },
    OAuthClientSecretResponse: { schema: OAuthClientSecretResponse, ...schema },
    CreateOAuthClientRequest: { schema: CreateOAuthClientRequest, ...schema },
    UpdateOAuthClientRequest: { schema: UpdateOAuthClientRequest, ...schema },
    RotateOAuthClientSecretRequest: { schema: RotateOAuthClientSecretRequest, ...schema },
    AuditRecords: { schema: AuditRecords, ...schema },
  },
  [
    operation(
      'users',
      { method: 'GET', path: '/users', successStatus: 200, summary: 'List all users' },
      'Empty',
      'Users',
    ),
    operation(
      'createUser',
      {
        method: 'POST',
        path: '/users',
        successStatus: 201,
        summary: 'Create a user',
        parameters: [idempotency],
      },
      'CreateUserRequest',
      'UserCreatedResponse',
    ),
    operation(
      'getUser',
      { method: 'GET', path: '/users/:userId', successStatus: 200, summary: 'Get a user' },
      'Empty',
      'UserResponse',
    ),
    operation(
      'updateUser',
      {
        method: 'PATCH',
        path: '/users/:userId',
        successStatus: 200,
        summary: "Update a user's display name",
        parameters: [idempotency],
      },
      'UpdateUserRequest',
      'UserResponse',
    ),
    operation(
      'archiveUser',
      {
        method: 'DELETE',
        path: '/users/:userId',
        successStatus: 204,
        summary: 'Archive a user',
        parameters: [idempotency],
      },
      'Empty',
      'Empty',
    ),
    operation(
      'organizations',
      {
        method: 'GET',
        path: '/organizations',
        successStatus: 200,
        summary: 'List all organizations',
      },
      'Empty',
      'Organizations',
    ),
    operation(
      'createOrganization',
      {
        method: 'POST',
        path: '/organizations',
        successStatus: 201,
        summary: 'Create an organization',
        parameters: [idempotency],
      },
      'CreateOrganizationRequest',
      'OrganizationCreatedResponse',
    ),
    operation(
      'getOrganization',
      {
        method: 'GET',
        path: '/organizations/:slug',
        successStatus: 200,
        summary: 'Get an organization',
      },
      'Empty',
      'OrganizationResponse',
    ),
    operation(
      'updateOrganization',
      {
        method: 'PATCH',
        path: '/organizations/:slug',
        successStatus: 200,
        summary: "Update an organization's display name",
        parameters: [idempotency],
      },
      'UpdateOrganizationRequest',
      'OrganizationResponse',
    ),
    operation(
      'deleteOrganization',
      {
        method: 'DELETE',
        path: '/organizations/:slug',
        successStatus: 204,
        summary: 'Delete an organization',
        parameters: [idempotency],
      },
      'Empty',
      'Empty',
    ),
    operation(
      'getMembership',
      {
        method: 'GET',
        path: '/organizations/:slug/members/:userId',
        successStatus: 200,
        summary: 'Get an organization membership',
      },
      'Empty',
      'MembershipResponse',
    ),
    operation(
      'putMembership',
      {
        method: 'PUT',
        path: '/organizations/:slug/members/:userId',
        successStatus: 204,
        summary: 'Upsert organization membership',
        parameters: [idempotency],
      },
      'MembershipRequest',
      'Empty',
    ),
    operation(
      'deleteMembership',
      {
        method: 'DELETE',
        path: '/organizations/:slug/members/:userId',
        successStatus: 204,
        summary: 'Remove organization membership',
        parameters: [idempotency],
      },
      'Empty',
      'Empty',
    ),
    operation(
      'oauthClients',
      {
        method: 'GET',
        path: '/oauth-clients',
        successStatus: 200,
        summary: 'List all OAuth clients',
      },
      'Empty',
      'OAuthClients',
    ),
    operation(
      'createOAuthClient',
      {
        method: 'POST',
        path: '/oauth-clients',
        successStatus: 201,
        summary: 'Create an OAuth client',
        parameters: [idempotency],
      },
      'CreateOAuthClientRequest',
      'OAuthClientSecretResponse',
    ),
    operation(
      'getOAuthClient',
      {
        method: 'GET',
        path: '/oauth-clients/:clientId',
        successStatus: 200,
        summary: 'Get an OAuth client',
      },
      'Empty',
      'OAuthClientResponse',
    ),
    operation(
      'updateOAuthClient',
      {
        method: 'PUT',
        path: '/oauth-clients/:clientId',
        successStatus: 200,
        summary: 'Update OAuth client metadata',
        parameters: [idempotency],
      },
      'UpdateOAuthClientRequest',
      'OAuthClientResponse',
    ),
    operation(
      'revokeOAuthClient',
      {
        method: 'DELETE',
        path: '/oauth-clients/:clientId',
        successStatus: 204,
        summary: 'Revoke an OAuth client',
        parameters: [idempotency],
      },
      'Empty',
      'Empty',
    ),
    operation(
      'rotateOAuthClientSecret',
      {
        method: 'POST',
        path: '/oauth-clients/:clientId/rotate-secret',
        successStatus: 200,
        summary: 'Rotate an OAuth client secret',
        parameters: [idempotency],
      },
      'RotateOAuthClientSecretRequest',
      'OAuthClientSecretResponse',
    ),
    operation(
      'audit',
      { method: 'GET', path: '/audit', successStatus: 200, summary: 'List audit records' },
      'Empty',
      'AuditRecords',
    ),
  ],
);
